model_params:
  name: 'betaVAE'
  in_channels: 1
  latent_dim: 16
  beta: 4
  gamma: 1000
  max_capacity: 25
  Capacity_max_iter: 1e5
  loss_type: 'H'
  hidden_dims: [8, 16, 32, 64, 128]


data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4
  batch_size: 10
  iterations: 100


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
#  devices: [ 0 ]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "betaVAE"
